#ifndef CONSTANTS_GLSL_
#define CONSTANTS_GLSL_

const uint BINDING_SCENE = 0;
const uint BINDING_OUTPUT = 1;
const uint BINDING_SETTINGS = 2;
const uint BINDING_CAMERA = 3;
const uint BINDING_VERTEX_BUFFERS = 4;
const uint BINDING_INDEX_BUFFERS = 5;
const uint BINDING_INSTANCE_BUFFERS = 6;
const uint BINDING_MATERIAL_BUFFERS = 7;
const uint BINDING_TEXTURE_SAMPLERS = 8;
const uint BINDING_LIGHT_BUFFER = 9;

#endif